name: Run Python Scraper

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to scrape (e.g., SPX, SOX)'
        required: true
        default: 'SPX'
      date:
        description: 'Date to scrape (YYYY/MM/DD or now)'
        required: true
        default: 'now'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          TARGET: ${{ github.event.inputs.target }}
          DATE: ${{ github.event.inputs.date }}
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'LazyBug-Actions-Bot'
          git config --global user.email 'actions-bot@github.com'
          git add data/*.csv
          git commit -m "[LazyBug Bot] Update ${TARGET} data on $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
